import { useEffect, useRef, useState } from 'react'
import mapboxgl from 'mapbox-gl'
import 'mapbox-gl/dist/mapbox-gl.css'
import SessionPrompt from './SessionPrompt.tsx'
import InvalidInvitePrompt from './InvalidInvitePrompt.tsx'
import Legend from './Legend.tsx'
import MemberManager from './MemberManager.tsx'
import ReplayControls from './ReplayControls.tsx'
import MapPlayButton from './MapPlayButton.tsx'
import LoadRouteButton from './LoadRouteButton.tsx'
import AuthPrompt from './AuthPrompt.tsx'
import LegalPage from './LegalPage.tsx'
import AdminPanel from './AdminPanel.tsx'
import AccountSettings from './AccountSettings.tsx'
import LandingPage from './LandingPage.tsx'
import InitialsBadge from './components/InitialsBadge.tsx'
import { useRunnerMarkers } from './useRunnerMarkers.ts'
import { useRouteLayer } from './useRouteLayer.ts'
import { useSessionTimeline } from './useSessionTimeline.ts'
import { parseGpxCoordinates } from './gpx.ts'
import { apiHeaders } from './apiHeaders.ts'
import { canManageMembersForRole, shouldShowAuthPrompt, shouldShowSessionPrompt } from './sessionState.ts'
import type { AuthResponse, AuthenticatedUser, SessionMembership } from './types.ts'

mapboxgl.accessToken = import.meta.env.VITE_MAPBOX_TOKEN as string

const POLL_INTERVAL_MS: number = parseInt(import.meta.env.VITE_POLL_INTERVAL_MS ?? '5000', 10)
const SERVER_URL: string = import.meta.env.VITE_SERVER_URL ?? '/api'
const APP_VERSION = import.meta.env.VITE_APP_VERSION ?? 'v-local'
const APP_UPDATED_AT = import.meta.env.VITE_APP_UPDATED_AT ?? 'Updated local'
const VERSION_LABEL = `${APP_VERSION} · ${APP_UPDATED_AT}`
const AUTH_TOKEN_KEY = 'userAccessToken'
const AUTH_EXPIRES_KEY = 'userAccessTokenExpiresAt'
const AUTH_USER_KEY = 'user'

interface RouteState {
  sessionName: string | null
  inviteCode: string | null
  legalPage: 'privacy' | 'terms' | null
  isAdmin: boolean
  isLanding: boolean
}

// The only routes ever generated by the app: '/' (landing) and '/code/{code}' (shared via the
// iOS ShareLink). '/{sessionName}' isn't shared either, but stays reachable because joining a
// session rewrites the address bar to it (see handleMembershipSelect) so reloads keep working.
function parseUrl(): RouteState {
  const parts = window.location.pathname.replace(/^\//, '').split('/')
  const norm = (s: string) => s.toUpperCase() || null
  if (parts[0] === 'admin') return { sessionName: null, inviteCode: null, legalPage: null, isAdmin: true, isLanding: false }
  if (parts[0] === 'privacy') return { sessionName: null, inviteCode: null, legalPage: 'privacy', isAdmin: false, isLanding: false }
  if (parts[0] === 'terms') return { sessionName: null, inviteCode: null, legalPage: 'terms', isAdmin: false, isLanding: false }
  if (parts[0] === 'code') return { sessionName: null, inviteCode: norm(parts[1] ?? ''), legalPage: null, isAdmin: false, isLanding: false }
  if (!parts[0]) return { sessionName: null, inviteCode: null, legalPage: null, isAdmin: false, isLanding: true }
  return { sessionName: norm(parts[0]), inviteCode: null, legalPage: null, isAdmin: false, isLanding: false }
}

function readStoredAuth(): AuthResponse | null {
  const accessToken = localStorage.getItem(AUTH_TOKEN_KEY)
  if (!accessToken) return null

  const expiresAt = localStorage.getItem(AUTH_EXPIRES_KEY)
  const expiresAtMs = expiresAt ? Date.parse(expiresAt) : NaN
  if (!Number.isFinite(expiresAtMs) || expiresAtMs <= Date.now()) {
    clearStoredAuth()
    return null
  }

  const storedUser = localStorage.getItem(AUTH_USER_KEY)
  let user: AuthenticatedUser = { userId: '', username: '', displayName: '' }
  if (storedUser) {
    try {
      user = JSON.parse(storedUser) as AuthenticatedUser
    } catch {
      localStorage.removeItem(AUTH_USER_KEY)
    }
  }

  return { accessToken, expiresAt, user }
}

function clearStoredAuth() {
  localStorage.removeItem(AUTH_TOKEN_KEY)
  localStorage.removeItem(AUTH_EXPIRES_KEY)
  localStorage.removeItem(AUTH_USER_KEY)
  sessionStorage.removeItem(AUTH_TOKEN_KEY)
  sessionStorage.removeItem(AUTH_EXPIRES_KEY)
  sessionStorage.removeItem(AUTH_USER_KEY)
}

export default function App() {
  const containerRef = useRef<HTMLDivElement>(null)
  const mapRef = useRef<mapboxgl.Map | null>(null)
  const { sessionName: initialName, inviteCode, legalPage, isAdmin, isLanding } = parseUrl()
  const [sessionName, setSessionName] = useState<string | null>(initialName)
  const [auth, setAuth] = useState<AuthResponse | null>(() => readStoredAuth())
  const [memberships, setMemberships] = useState<SessionMembership[]>([])
  const [membershipsLoaded, setMembershipsLoaded] = useState(false)
  const [showMembers, setShowMembers] = useState(false)
  const [showSettings, setShowSettings] = useState(false)
  const [routeCoordinates, setRouteCoordinates] = useState<[number, number][] | null>(null)
  const accessToken = auth?.accessToken ?? null

  useEffect(() => {
    if (legalPage || isLanding || !containerRef.current) return

    const map = new mapboxgl.Map({
      container: containerRef.current,
      style: 'mapbox://styles/mapbox/streets-v12',
      center: [174.7762, -41.2865], // Wellington, NZ - default before any session/positions load
      zoom: 13,
    })

    map.addControl(new mapboxgl.NavigationControl(), 'top-right')
    map.addControl(new mapboxgl.GeolocateControl({
      positionOptions: { enableHighAccuracy: true },
      trackUserLocation: true,
    }), 'top-right')

    mapRef.current = map
    return () => {
      map.remove()
      mapRef.current = null
    }
  }, [legalPage])

  useEffect(() => {
    if (!accessToken) {
      setMemberships([])
      setMembershipsLoaded(false)
      return
    }

    let cancelled = false
    setMembershipsLoaded(false)

    async function loadMemberships() {
      try {
        const response = await fetch(`${SERVER_URL}/me/sessions`, {
          headers: apiHeaders(accessToken),
        })

        if (cancelled) return

        if (response.status === 401) {
          handleSignOut()
          return
        }

        if (response.ok) {
          setMemberships(await response.json() as SessionMembership[])
        }
      } finally {
        if (!cancelled) setMembershipsLoaded(true)
      }
    }

    void loadMemberships()
    return () => { cancelled = true }
  }, [accessToken])

  // Invite-code URLs (/code/{code}) never carry a sessionName, so a membership from before the
  // session ended can only be found by matching the invite code itself — otherwise a returning
  // member always falls through to a fresh join, which 410s once the session is archived.
  const activeMembership = memberships.find(membership =>
    inviteCode ? membership.inviteCode === inviteCode : membership.sessionName === sessionName,
  ) ?? null
  const sessionId = activeMembership?.sessionId ?? null
  const hasSessionMembership = (sessionName || inviteCode) ? activeMembership !== null : false
  const canManageMembers = canManageMembersForRole(activeMembership?.role)
  const showSessionPrompt = shouldShowSessionPrompt({
    accessToken,
    membershipsLoaded,
    inviteCode,
    sessionName,
    hasSessionMembership,
  })

  const timeline = useSessionTimeline(
    hasSessionMembership ? sessionId : null,
    SERVER_URL,
    accessToken,
    POLL_INTERVAL_MS,
    !accessToken ? inviteCode : null,
  )

  const { allRunners, followRunner, fitAll } = useRunnerMarkers(
    mapRef,
    timeline.positions,
    timeline.virtualNowMs,
    timeline.runnersWithGpsSignalLoss,
    timeline.runnersWithGap,
    timeline.runnersSleeping,
  )
  useRouteLayer(mapRef, routeCoordinates, timeline.runStartMs === null)

  const routeBase = !accessToken && inviteCode
    ? `${SERVER_URL}/session-invites/${inviteCode}`
    : hasSessionMembership && sessionId
    ? `${SERVER_URL}/sessions/${sessionId}`
    : null

  useEffect(() => {
    setRouteCoordinates(null)
    if (!routeBase) return

    let cancelled = false
    async function loadRoute() {
      const response = await fetch(`${routeBase}/route`, {
        headers: apiHeaders(accessToken),
      })
      if (cancelled || !response.ok) return
      const gpx = await response.text()
      setRouteCoordinates(parseGpxCoordinates(gpx))
    }

    void loadRoute()
    return () => { cancelled = true }
  }, [routeBase, accessToken])

  // Membership already carries ownerDisplayName once the viewer has one; an unauthenticated
  // invite-code viewer has no membership at all, so fetch the same info from the tokenless
  // session-info endpoint instead.
  const [inviteOwnerDisplayName, setInviteOwnerDisplayName] = useState<string | null>(null)
  useEffect(() => {
    setInviteOwnerDisplayName(null)
    if (accessToken || !inviteCode) return

    let cancelled = false
    fetch(`${SERVER_URL}/session-invites/${inviteCode}`)
      .then(res => (res.ok ? res.json() as Promise<{ ownerDisplayName: string }> : null))
      .then(info => { if (!cancelled && info) setInviteOwnerDisplayName(info.ownerDisplayName) })
      .catch(() => undefined)
    return () => { cancelled = true }
  }, [accessToken, inviteCode])

  const ownerDisplayName = activeMembership?.ownerDisplayName ?? inviteOwnerDisplayName

  async function uploadRoute(file: File) {
    if (!sessionId || !accessToken) return
    const gpxText = await file.text()
    const response = await fetch(`${SERVER_URL}/sessions/${sessionId}/route`, {
      method: 'POST',
      headers: apiHeaders(accessToken),
      body: gpxText,
    })
    if (response.ok) {
      setRouteCoordinates(parseGpxCoordinates(gpxText))
    } else if (response.status === 403) {
      window.alert('Only the session owner can set the route.')
    } else {
      window.alert('Failed to upload route.')
    }
  }

  function handleAuth(nextAuth: AuthResponse) {
    clearStoredAuth()
    localStorage.setItem(AUTH_TOKEN_KEY, nextAuth.accessToken)
    localStorage.setItem(AUTH_EXPIRES_KEY, nextAuth.expiresAt)
    localStorage.setItem(AUTH_USER_KEY, JSON.stringify(nextAuth.user))
    setAuth(nextAuth)
  }

  function handleSignOut() {
    const tokenToRevoke = accessToken
    if (tokenToRevoke) {
      void fetch(`${SERVER_URL}/auth/logout`, {
        method: 'POST',
        headers: apiHeaders(tokenToRevoke),
      }).catch(() => undefined)
    }

    clearStoredAuth()
    setAuth(null)
    setMemberships([])
    setSessionName(null)
    setShowMembers(false)
    setShowSettings(false)
  }

  async function handleDeleteAccount() {
    if (!accessToken) return
    let response: Response
    try {
      response = await fetch(`${SERVER_URL}/me`, {
        method: 'DELETE',
        headers: apiHeaders(accessToken),
      })
    } catch {
      window.alert('Delete account failed: network error')
      throw new Error('Delete account failed: network error')
    }

    if (!response.ok) {
      window.alert(`Delete account failed: HTTP ${response.status}`)
      throw new Error(`Delete account failed: HTTP ${response.status}`)
    }

    clearStoredAuth()
    setAuth(null)
    setMemberships([])
    setSessionName(null)
    setShowMembers(false)
    setShowSettings(false)
  }

  function handleMembershipSelect(membership: SessionMembership) {
    window.history.replaceState(null, '', `/${membership.sessionName}`)
    setSessionName(membership.sessionName)
    setShowMembers(false)
  }

  if (isAdmin) {
    return <AdminPanel serverUrl={SERVER_URL} />
  }

  if (legalPage) {
    return <LegalPage kind={legalPage} />
  }

  if (isLanding) {
    return <LandingPage />
  }

  return (
    <>
      <div ref={containerRef} style={{ width: '100%', height: '100%' }} />
      <div style={versionBadge}>
        <span>{VERSION_LABEL}</span>
        <a href="/privacy" style={legalLink}>Privacy</a>
        <a href="/terms" style={legalLink}>Terms</a>
      </div>
      {auth && (
        <div style={accountBar}>
          <span>{auth.user.displayName || auth.user.username}</span>
          {canManageMembers && (
            <button type="button" style={signOutButton} onClick={() => setShowMembers(true)}>Members</button>
          )}
          {hasSessionMembership && <LoadRouteButton onLoadRoute={uploadRoute} style={signOutButton} />}
          <button type="button" style={signOutButton} onClick={() => setShowSettings(true)}>Settings</button>
          <button type="button" style={signOutButton} onClick={handleSignOut}>Sign out</button>
        </div>
      )}
      <Legend runners={allRunners} onRunnerClick={followRunner} onFitAll={fitAll} belowAccountBar={!!auth} />
      {!timeline.invalidInvite && timeline.runStartMs !== null && (sessionName || (!accessToken && inviteCode)) && (
        <>
          <ReplayControls timeline={timeline} />
          {!timeline.following && !timeline.playing && <MapPlayButton onPlay={timeline.play} />}
        </>
      )}
      {timeline.gpsWarning && !timeline.invalidInvite && (hasSessionMembership || (!accessToken && inviteCode)) && (
        <div style={gpsWarningToast}>
          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" style={{ flexShrink: 0 }}>
            <path
              d="M12 3.5 L22 20.5 H2 Z"
              fill="none"
              stroke="#fff"
              strokeWidth="2"
              strokeLinejoin="round"
            />
            <rect x="11.1" y="9.5" width="1.8" height="6" rx="0.9" fill="#fff" />
            <circle cx="12" cy="17.5" r="1.1" fill="#fff" />
          </svg>
          <span>{timeline.gpsWarning}</span>
        </div>
      )}
      {!timeline.invalidInvite && !timeline.error && timeline.runStartMs === null &&
        (sessionName || (!accessToken && inviteCode)) && (
        <div style={notStartedToast}>
          {ownerDisplayName && (
            <div style={notStartedToastLine}>
              <span>Created by </span>
              <InitialsBadge name={ownerDisplayName} />
            </div>
          )}
          <div style={notStartedToastLine}>The session hasn&rsquo;t started yet.</div>
        </div>
      )}
      {timeline.error && !timeline.invalidInvite && (hasSessionMembership || (!accessToken && inviteCode)) && (
        <div style={statusToast}>{timeline.error}</div>
      )}
      {timeline.invalidInvite && (
        <InvalidInvitePrompt message={timeline.error ?? 'Invite not found.'} />
      )}
      {shouldShowAuthPrompt(accessToken, inviteCode) && <AuthPrompt serverUrl={SERVER_URL} onAuth={handleAuth} />}
      {accessToken && showSessionPrompt && (
        <SessionPrompt
          serverUrl={SERVER_URL}
          accessToken={accessToken}
          memberships={memberships}
          requestedSessionName={inviteCode ? undefined : sessionName}
          initialInviteCode={inviteCode}
          autoJoinDisplayName={inviteCode ? auth?.user.displayName ?? '' : undefined}
          onSelect={handleMembershipSelect}
          onMembershipsChanged={setMemberships}
        />
      )}
      {accessToken && canManageMembers && activeMembership && showMembers && (
        <MemberManager
          serverUrl={SERVER_URL}
          accessToken={accessToken}
          membership={activeMembership}
          onClose={() => setShowMembers(false)}
        />
      )}
      {auth && showSettings && (
        <AccountSettings
          displayName={auth.user.displayName || auth.user.username}
          onClose={() => setShowSettings(false)}
          onDeleteAccount={handleDeleteAccount}
        />
      )}
    </>
  )
}


const accountBar: React.CSSProperties = {
  position: 'absolute',
  top: 12,
  left: 12,
  zIndex: 8,
  display: 'flex',
  alignItems: 'center',
  gap: 8,
  background: '#fff',
  color: '#24292f',
  borderRadius: 6,
  boxShadow: '0 0 0 2px rgba(0,0,0,0.1)',
  padding: '6px 8px',
  fontFamily: 'system-ui, sans-serif',
  fontSize: '0.85rem',
}

const versionBadge: React.CSSProperties = {
  position: 'absolute',
  left: 12,
  bottom: 12,
  zIndex: 7,
  maxWidth: 'min(620px, calc(100vw - 96px))',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap',
  display: 'flex',
  alignItems: 'center',
  gap: 8,
  background: 'rgba(255,255,255,0.92)',
  color: '#57606a',
  borderRadius: 4,
  boxShadow: '0 0 0 1px rgba(0,0,0,0.1)',
  padding: '4px 7px',
  fontFamily: 'system-ui, sans-serif',
  fontSize: '0.75rem',
}

const legalLink: React.CSSProperties = {
  flex: '0 0 auto',
  color: '#1f6feb',
  textDecoration: 'none',
}

const signOutButton: React.CSSProperties = {
  border: '1px solid #d0d7de',
  borderRadius: 4,
  background: '#f6f8fa',
  color: '#24292f',
  cursor: 'pointer',
  fontFamily: 'system-ui, sans-serif',
  fontSize: '0.8rem',
  padding: '3px 6px',
}

const notStartedToast: React.CSSProperties = {
  position: 'absolute',
  left: '50%',
  bottom: 100,
  transform: 'translateX(-50%)',
  zIndex: 8,
  maxWidth: '92vw',
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  gap: 4,
  background: '#fff',
  color: '#57606a',
  borderRadius: 6,
  boxShadow: '0 0 0 2px rgba(0,0,0,0.1)',
  padding: '8px 14px',
  fontFamily: 'system-ui, sans-serif',
  fontSize: '0.9rem',
}

const notStartedToastLine: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 6,
  whiteSpace: 'nowrap',
}

const statusToast: React.CSSProperties = {
  position: 'absolute',
  left: '50%',
  bottom: 88,
  transform: 'translateX(-50%)',
  zIndex: 8,
  maxWidth: 'min(420px, 92vw)',
  background: '#fff',
  color: '#92400e',
  borderRadius: 6,
  boxShadow: '0 0 0 2px rgba(0,0,0,0.1)',
  padding: '8px 12px',
  fontFamily: 'system-ui, sans-serif',
  fontSize: '0.9rem',
}

const gpsWarningToast: React.CSSProperties = {
  position: 'absolute',
  left: '50%',
  bottom: 130,
  transform: 'translateX(-50%)',
  zIndex: 8,
  maxWidth: 'min(420px, 92vw)',
  display: 'flex',
  alignItems: 'center',
  gap: 6,
  background: '#dc2626',
  color: '#fff',
  borderRadius: 6,
  boxShadow: '0 0 0 2px rgba(0,0,0,0.1)',
  padding: '8px 12px',
  fontFamily: 'system-ui, sans-serif',
  fontSize: '0.85rem',
}
