name: dot-watcher-server
port: 8080
hostname: dot-watcher-server.skelstar.io
env:
  - name: RecordingsPath
    value: /data/recordings
  - name: DbPath
    value: /data/db/dotwatcher.db
  - name: SEQ_URL
    value: http://seq.seq.svc.cluster.local:5341
volumes:
  - name: recordings
    mountPath: /data/recordings
    size: 1Gi
  - name: db
    mountPath: /data/db
    size: 100Mi
