<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DotWatcher.Server</RootNamespace>
    <AssemblyName>DotWatcher.Server</AssemblyName>
  </PropertyGroup>
</Project>
